---
kind: pipeline
name: build-image
type: docker
trigger:
  event: [ push, custom ]
  branch: [ main ]

steps:

- name: build
  image: node:alpine
  commands:
    - npm install

# - name: test
#   image: node:alpine
#   commands:
#     - npm test

- name: publish
  image: plugins/docker
  settings:
    password:
      from_secret: local_docker_hub_password
    repo: akoptelov/mina-load-generator
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: local_docker_hub_username

