kind: pipeline
name: build-image
type: docker
trigger:
  event: [ push ]
  branch: [ main ]

steps:

- name: build
  image: node:alpine
  commands:
    - npm install

- name: test
  image: node:alpine
  commands:
    - npm test

- name: publish-send
  image: plugins/docker
  settings:
    password:
      from_secret: local_docker_hub_password
    repo: akoptelov/mina-sample-zkapp
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: local_docker_hub_username

- name: publish-jobs-controller
  image: plugins/docker
  settings:
    context: jobs-controller
    password:
      from_secret: local_docker_hub_password
    repo: akoptelov/mina-sample-zkapp-controller
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: local_docker_hub_username
