---
kind: pipeline
name: build-image
type: docker
trigger:
  event: [ push ]
  branch: [ main ]

steps:

- name: build
  image: node:alpine
  commands:
    - npm install

- name: test
  image: node:alpine
  commands:
    - npm test

- name: publish-send
  image: plugins/docker
  settings:
    password:
      from_secret: local_docker_hub_password
    repo: akoptelov/mina-sample-zkapp
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: local_docker_hub_username

- name: publish-jobs-controller
  image: plugins/docker
  settings:
    context: jobs-controller
    dockerfile: jobs-controller/Dockerfile
    password:
      from_secret: local_docker_hub_password
    repo: akoptelov/mina-sample-zkapp-controller
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
    username:
      from_secret: local_docker_hub_username

---
kind: pipeline
name: run-zkapps
type: docker

trigger:
  event: [ custom ]

environment:
  RELEASE_NAME: zkapps-drone-${DRONE_BUILD_NUMBER}
  SUFFIX: ${DRONE_BUILD_NUMBER}

steps:

- name: configure
  image: alpine/k8s:1.25.6
  environment:
    DRONE_KUBECONFIG:
      from_secret: local_kubeconfig
    KUBECONFIG: kube-config
  commands:
  - umask 0077
  - mkdir -p $HOME/.kube
  - echo "$DRONE_KUBECONFIG" > kube-config
  - kubectl config set-context --current --namespace $${NAMESPACE:-default}

- name: start
  image: alpine/k8s:1.25.6
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm install $${RELEASE_NAME} . $${COUNT:+--set=transactionCount=$${COUNT}} --set=suffix=$${SUFFIX} --set=parallelism=1

- name: run
  image: alpine/k8s:1.25.6
  environment:
    KUBECONFIG: kube-config
  commands:
  - |
    for t in $(seq 10); do
        kubectl logs jobs/send-zkapps-$${SUFFIX} --container=send --follow && exit
        echo "Waiting for send container..."
        sleep 5
    done
    echo "Failed to wait for send container"
    exit 1

- name: finish
  image: alpine/k8s:1.25.6
  environment:
    KUBECONFIG: kube-config
  commands:
  - kubectl wait --for=jsonpath='{.status.ready}'=0 job/send-zkapps-$${SUFFIX} --timeout=180s
  - ERR=$$?
  - kubectl get job/send-zkapps-$${SUFFIX}-o jsonpath='{.status.conditions[*].message}'
  - exit $$ERR

- name: clean-up
  image: alpine/k8s:1.25.6
  environment:
    KUBECONFIG: kube-config
  commands:
  - helm uninstall $${RELEASE_NAME}
  when:
    status:
    - success
    - failure
