---
kind: pipeline
name: build-image
type: docker
trigger:
  event: [ push, custom ]
  branch: [ main ]

steps:

- name: build
  image: node:alpine
  commands:
    - npm install

- name: test
  image: node:alpine
  commands:
    - npm test

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
    repo: openmina/mina-load-generator
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
