{{ if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "load-generator.fullname" . }}
  labels:
    {{- include "load-generator.labels" . | nindent 4 }}
data:
  nodes.json: |
    {{ .Values.nodes | toJson }}
  accounts.json: |
    {{ .Values.accounts | toJson }}
{{ end }}
