apiVersion: batch/v1
kind: Job
metadata:
  name: send-zkapps
spec:
  parallelism: {{ $.Values.parallelism | default 1 }}
  template:
    metadata:
      labels:
        app: send-zkapps
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values: [ send-zkapps ]
      #       topologyKey: "kubernetes.io/hostname"
      runtimeClassName: kata-clh
      initContainers:
      - name: controller-is-ready
        image: alpine:latest
        args:
        - sh
        - -c
        - while ! nc -vz controller 80; do sleep 1; done
      containers:
      - name: send
        image: {{ $.Values.jobImage.repository }}:{{ $.Values.jobImage.tag | default "latest" }}
        imagePullPolicy: {{ $.Values.jobImage.pullPolicy }}
        args:
        - job
        - --controller=http://controller/
        - --count={{ add (div (sub ($.Values.transactionCount | default 1) 1) ($.Values.parallelism | default 1)) 1 }}
        resources:
          requests:
            {{ if $.Values.cpu }}
            cpu: {{ $.Values.cpu }}
            {{ end }}
            {{ if $.Values.mem }}
            memory: {{ $.Values.mem }}
            {{ end }}
          limits:
            {{ if $.Values.cpu }}
            cpu: {{ $.Values.cpu }}
            {{ end }}
            {{ if $.Values.mem }}
            memory: {{ $.Values.mem }}
            {{ end }}
      restartPolicy: {{ $.Values.restartPolicy | default "OnFailure" }}
