#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      -
        name: Git checkout
        uses: actions/checkout@v3
      -
        name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      -
        name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true

  docker:
    runs-on: ubuntu-latest
    # needs: [test]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            openmina/mina-load-generator
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,format=short,prefix={{branch}}-
            type=raw,value={{branch}}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
